name: Trivy IaC Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  trivy:
    name: Run Trivy IaC Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Trivy
      run: |
        echo "Installing Trivy..."
        wget https://github.com/aquasecurity/trivy/releases/download/v0.34.1/trivy_0.34.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.34.1_Linux-64bit.deb
        trivy --version

    - name: Run Trivy IaC Scan
      run: |
        trivy iac --format json --output trivy_iac_report.json .

    - name: Upload Trivy IaC Report
      uses: actions/upload-artifact@v3
      with:
        name: trivy-iac-report
        path: trivy_iac_report.json
