name: TruffleHog Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  trufflehog:
    name: Run TruffleHog Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install TruffleHog
      run: |
        python -m pip install --upgrade pip
        pip install truffleHog

    - name: Verify TruffleHog Installation
      run: |
        echo "Checking TruffleHog version..."
        trufflehog --version

    - name: Run TruffleHog Scan
      run: |
        echo "Running TruffleHog scan..."
        trufflehog --json https://github.com/Twist-hash/VulnerableApp.git > trufflehog_report.json || { echo 'TruffleHog scan failed'; exit 1; }

    - name: Display TruffleHog Report
      run: |
        echo "Displaying TruffleHog report..."
        cat trufflehog_report.json || { echo 'Failed to display TruffleHog report'; exit 1; }

    - name: Upload TruffleHog Report
      uses: actions/upload-artifact@v3
      with:
        name: trufflehog-report
        path: trufflehog_report.json
        
    - name: Upload TruffleHog Report
      uses: actions/upload-artifact@v3
      with:
        name: trufflehog-report
        path: trufflehog_report.json
